//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCmdPal.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred during translation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_message_during_translation {
            get {
                return ResourceManager.GetString("error_message_during_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many requests. Please try again later.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_too_many_requests {
            get {
                return ResourceManager.GetString("error_too_many_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string history_1 {
            get {
                return ResourceManager.GetString("history_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string history_10 {
            get {
                return ResourceManager.GetString("history_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string history_20 {
            get {
                return ResourceManager.GetString("history_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string history_5 {
            get {
                return ResourceManager.GetString("history_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string history_none {
            get {
                return ResourceManager.GetString("history_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid API key. Please check the API key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string invalid_api_key {
            get {
                return ResourceManager.GetString("invalid_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeepL API Key
        ///Please enter the following format
        ///DeepL-Auth-Key {API KEY}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plugin_deepL_api_key {
            get {
                return ResourceManager.GetString("plugin_deepL_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target language to use as the default.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plugin_default_target_language_code_description {
            get {
                return ResourceManager.GetString("plugin_default_target_language_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Target Language Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plugin_default_target_language_code_title {
            get {
                return ResourceManager.GetString("plugin_default_target_language_code_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determines the number of history items to show from previous Translation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plugin_show_history {
            get {
                return ResourceManager.GetString("plugin_show_history", resourceCulture);
            }
        }
    }
}
